name: Update Readme Latest Blog
on:
  workflow_dispatch:
  schedule:
    # Runs every 2 hour
    - cron: "0 */2 * * *"

jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          max_post_count: 5
          feed_list: "https://blog.metaprogramming.space/rss.xml"
